# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c18b71e5988913e23ebd15d7fd29864a"
application_url = "https://thunder-storm-mba-annual.trycloudflare.com"
embedded = true
name = "draft-order"
handle = "draft-order-29"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "frontend-test-sinedino.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_products,read_customers,read_orders,read_cart_transforms"

[auth]
redirect_urls = [
  "https://thunder-storm-mba-annual.trycloudflare.com/auth/callback",
  "https://thunder-storm-mba-annual.trycloudflare.com/auth/shopify/callback",
  "https://thunder-storm-mba-annual.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://thunder-storm-mba-annual.trycloudflare.com"
subpath = "draft-order"
prefix = "apps"
